using SampSharp.GameMode.Definitions;
using SampSharp.GameMode.Display;
using System;
using System.Collections.Generic;
using System.Text;
using SampSharp.GameMode;


namespace SampSharpGameMode1
{
    internal class Inventory
    {
        
        public static void CreateInventory(Player p) {
            //________________________INVENTORY_________________________________________________________________________
            /**
inventorybackplate[playerid] = CreatePlayerTextDraw(playerid, 476.000000, 110.000000, "_");
PlayerTextDrawFont(playerid, inventorybackplate[playerid], 1);
PlayerTextDrawLetterSize(playerid, inventorybackplate[playerid], 0.600000, 36.599918);
PlayerTextDrawTextSize(playerid, inventorybackplate[playerid], 298.500000, 208.500000);
PlayerTextDrawSetOutline(playerid, inventorybackplate[playerid], 1);
PlayerTextDrawSetShadow(playerid, inventorybackplate[playerid], 0);
PlayerTextDrawAlignment(playerid, inventorybackplate[playerid], 2);
PlayerTextDrawColor(playerid, inventorybackplate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, inventorybackplate[playerid], 255);
PlayerTextDrawBoxColor(playerid, inventorybackplate[playerid], 181);
PlayerTextDrawUseBox(playerid, inventorybackplate[playerid], 1);
PlayerTextDrawSetProportional(playerid, inventorybackplate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, inventorybackplate[playerid], 0);
**/
            PlayerTextDraw inventoryBackPlate = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(476.0f, 110.0f), "_");
            inventoryBackPlate.Font = TextDrawFont.Normal;
            inventoryBackPlate.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 36.599918f);
            inventoryBackPlate.Width = 298.5f;
            inventoryBackPlate.Height = 208.5f;
            inventoryBackPlate.Outline = 1;
            inventoryBackPlate.Shadow = 0;
            inventoryBackPlate.Alignment = TextDrawAlignment.Center;
            inventoryBackPlate.ForeColor = -1;
            inventoryBackPlate.BackColor = 255;
            inventoryBackPlate.BoxColor = 181;
            inventoryBackPlate.UseBox = true;
            inventoryBackPlate.Proportional = true;
            inventoryBackPlate.Selectable = false;
            inventoryBackPlate.Show();
            

            /**
playerbutton[playerid] = CreatePlayerTextDraw(playerid, 404.000000, 114.000000, "Preview_Model");
PlayerTextDrawFont(playerid, playerbutton[playerid], 5);
PlayerTextDrawLetterSize(playerid, playerbutton[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, playerbutton[playerid], 62.500000, 93.500000);
PlayerTextDrawSetOutline(playerid, playerbutton[playerid], 0);
PlayerTextDrawSetShadow(playerid, playerbutton[playerid], 0);
PlayerTextDrawAlignment(playerid, playerbutton[playerid], 1);
PlayerTextDrawColor(playerid, playerbutton[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, playerbutton[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, playerbutton[playerid], -16777103);
PlayerTextDrawUseBox(playerid, playerbutton[playerid], 0);
PlayerTextDrawSetProportional(playerid, playerbutton[playerid], 1);
PlayerTextDrawSetSelectable(playerid, playerbutton[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, playerbutton[playerid], 285);
PlayerTextDrawSetPreviewRot(playerid, playerbutton[playerid], -9.000000, 0.000000, -2.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, playerbutton[playerid], 1, 1);
            **/
            PlayerTextDraw playerButton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(404.0f, 114.0f), "Preview_Model");
            playerButton.Font = TextDrawFont.PreviewModel;
            playerButton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            playerButton.Width = 62.5f;
            playerButton.Height = 93.5f;
            playerButton.Outline = 0;
            playerButton.Shadow = 0;
            playerButton.Alignment = TextDrawAlignment.Left;
            playerButton.ForeColor = -1;
            playerButton.BackColor = -1094795651;
            playerButton.BoxColor = -16777103;
            playerButton.UseBox = false;
            playerButton.Proportional = true;
            playerButton.Selectable = true;
            playerButton.PreviewModel = 285;
            playerButton.PreviewRotation = new SampSharp.GameMode.Vector3(-9.0, 0.0, -2.0);
            playerButton.PreviewZoom = 1;

            /**
helmetTD[playerid] = CreatePlayerTextDraw(playerid, 375.000000, 114.000000, "Preview_Model");
PlayerTextDrawFont(playerid, helmetTD[playerid], 5);
PlayerTextDrawLetterSize(playerid, helmetTD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, helmetTD[playerid], 25.500000, 27.500000);
PlayerTextDrawSetOutline(playerid, helmetTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, helmetTD[playerid], 0);
PlayerTextDrawAlignment(playerid, helmetTD[playerid], 1);
PlayerTextDrawColor(playerid, helmetTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, helmetTD[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, helmetTD[playerid], -16777103);
PlayerTextDrawUseBox(playerid, helmetTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, helmetTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, helmetTD[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, helmetTD[playerid], 19141);
PlayerTextDrawSetPreviewRot(playerid, helmetTD[playerid], -3.000000, -90.000000, 15.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, helmetTD[playerid], 1, 1);
**/
            PlayerTextDraw helmetbutton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(375.0f, 114.0f), "Preview_Model");
            helmetbutton.Font = TextDrawFont.PreviewModel;
            helmetbutton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            helmetbutton.Width = 25.5f;
            helmetbutton.Height = 27.5f;
            helmetbutton.Outline = 0;
            helmetbutton.Shadow = 0;
            helmetbutton.Alignment = TextDrawAlignment.Left;
            helmetbutton.ForeColor = -1;
            helmetbutton.BackColor = -1094795651;
            helmetbutton.BoxColor = -16777103;
            helmetbutton.UseBox = false;
            helmetbutton.Proportional = true;
            helmetbutton.Selectable = true;
            helmetbutton.PreviewModel = 19141;
            helmetbutton.PreviewRotation = new SampSharp.GameMode.Vector3(-3.0, -90.0, 15.0);
            helmetbutton.PreviewZoom = 1;

            /**
rukzak[playerid] = CreatePlayerTextDraw(playerid, 375.000000, 180.000000, "Preview_Model");
PlayerTextDrawFont(playerid, rukzak[playerid], 5);
PlayerTextDrawLetterSize(playerid, rukzak[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, rukzak[playerid], 25.500000, 27.500000);
PlayerTextDrawSetOutline(playerid, rukzak[playerid], 0);
PlayerTextDrawSetShadow(playerid, rukzak[playerid], 0);
PlayerTextDrawAlignment(playerid, rukzak[playerid], 1);
PlayerTextDrawColor(playerid, rukzak[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, rukzak[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, rukzak[playerid], -16777103);
PlayerTextDrawUseBox(playerid, rukzak[playerid], 0);
PlayerTextDrawSetProportional(playerid, rukzak[playerid], 1);
PlayerTextDrawSetSelectable(playerid, rukzak[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, rukzak[playerid], 371);
PlayerTextDrawSetPreviewRot(playerid, rukzak[playerid], -9.000000, 0.000000, -2.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, rukzak[playerid], 1, 1);
**/
            PlayerTextDraw backpackButton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(375.0f, 180.0f), "Preview_Model");
            backpackButton.Font = TextDrawFont.PreviewModel;
            backpackButton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            backpackButton.Width = 25.5f;
            backpackButton.Height = 27.5f;
            backpackButton.Outline = 0;
            backpackButton.Shadow = 0;
            backpackButton.Alignment = TextDrawAlignment.Left;
            backpackButton.ForeColor = -1;
            backpackButton.BackColor = -1094795651;
            backpackButton.BoxColor = -16777103;
            backpackButton.UseBox = false;
            backpackButton.Proportional = true;
            backpackButton.Selectable = true;
            backpackButton.PreviewModel = 371;
            backpackButton.PreviewRotation = new SampSharp.GameMode.Vector3(-9.0, 0.0, -2.0);
            backpackButton.PreviewZoom = 1;
            /**
ARMOURTD[playerid] = CreatePlayerTextDraw(playerid, 375.000000, 147.000000, "Preview_Model");
PlayerTextDrawFont(playerid, ARMOURTD[playerid], 5);
PlayerTextDrawLetterSize(playerid, ARMOURTD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, ARMOURTD[playerid], 25.500000, 27.500000);
PlayerTextDrawSetOutline(playerid, ARMOURTD[playerid], 0);
PlayerTextDrawSetShadow(playerid, ARMOURTD[playerid], 0);
PlayerTextDrawAlignment(playerid, ARMOURTD[playerid], 1);
PlayerTextDrawColor(playerid, ARMOURTD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, ARMOURTD[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, ARMOURTD[playerid], -16777103);
PlayerTextDrawUseBox(playerid, ARMOURTD[playerid], 0);
PlayerTextDrawSetProportional(playerid, ARMOURTD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, ARMOURTD[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, ARMOURTD[playerid], 1242);
PlayerTextDrawSetPreviewRot(playerid, ARMOURTD[playerid], -9.000000, 0.000000, -2.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, ARMOURTD[playerid], 1, 1);
            **/
            PlayerTextDraw armourButton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(375.0f, 147.0f), "Preview_Model");
            armourButton.Font = TextDrawFont.PreviewModel;
            armourButton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            armourButton.Width = 25.5f;
            armourButton.Height = 27.5f;
            armourButton.Outline = 0;
            armourButton.Shadow = 0;
            armourButton.Alignment = TextDrawAlignment.Left;
            armourButton.ForeColor = -1;
            armourButton.BackColor = -1094795651;
            armourButton.BoxColor = -16777103;
            armourButton.UseBox = false;
            armourButton.Proportional = true;
            armourButton.Selectable = true;
            armourButton.PreviewModel = 1242;
            armourButton.PreviewRotation = new SampSharp.GameMode.Vector3(-9.0, 0.0, -2.0);
            armourButton.PreviewZoom = 1;

            /**
pagertxd[playerid] = CreatePlayerTextDraw(playerid, 407.000000, 186.000000, "Preview_Model");
PlayerTextDrawFont(playerid, pagertxd[playerid], 5);
PlayerTextDrawLetterSize(playerid, pagertxd[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, pagertxd[playerid], 17.000000, 17.500000);
PlayerTextDrawSetOutline(playerid, pagertxd[playerid], 0);
PlayerTextDrawSetShadow(playerid, pagertxd[playerid], 0);
PlayerTextDrawAlignment(playerid, pagertxd[playerid], 1);
PlayerTextDrawColor(playerid, pagertxd[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, pagertxd[playerid], 125);
PlayerTextDrawBoxColor(playerid, pagertxd[playerid], -16777103);
PlayerTextDrawUseBox(playerid, pagertxd[playerid], 0);
PlayerTextDrawSetProportional(playerid, pagertxd[playerid], 1);
PlayerTextDrawSetSelectable(playerid, pagertxd[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, pagertxd[playerid], 18875);
PlayerTextDrawSetPreviewRot(playerid, pagertxd[playerid], -81.000000, 0.000000, -179.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, pagertxd[playerid], 1, 1);
**/
            PlayerTextDraw pagerButton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(407.0f, 186.0f), "Preview_Model");
            pagerButton.Font = TextDrawFont.PreviewModel;
            pagerButton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            pagerButton.Width = 17.0f;
            pagerButton.Height = 17.5f;
            pagerButton.Outline = 0;
            pagerButton.Shadow = 0;
            pagerButton.Alignment = TextDrawAlignment.Left;
            pagerButton.ForeColor = -1;
            pagerButton.BackColor = 125;
            pagerButton.BoxColor = -16777103;
            pagerButton.UseBox = false;
            pagerButton.Proportional = true;
            pagerButton.Selectable = true;
            pagerButton.PreviewModel = 18875;
            pagerButton.PreviewRotation = new SampSharp.GameMode.Vector3(-81.0, 0.0, -179.0);
            pagerButton.PreviewZoom = 1;

            /**
achievementsbutton[playerid] = CreatePlayerTextDraw(playerid, 447.000000, 186.000000, "Preview_Model");
PlayerTextDrawFont(playerid, achievementsbutton[playerid], 5);
PlayerTextDrawLetterSize(playerid, achievementsbutton[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, achievementsbutton[playerid], 17.000000, 17.500000);
PlayerTextDrawSetOutline(playerid, achievementsbutton[playerid], 0);
PlayerTextDrawSetShadow(playerid, achievementsbutton[playerid], 0);
PlayerTextDrawAlignment(playerid, achievementsbutton[playerid], 1);
PlayerTextDrawColor(playerid, achievementsbutton[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, achievementsbutton[playerid], 125);
PlayerTextDrawBoxColor(playerid, achievementsbutton[playerid], -16777103);
PlayerTextDrawUseBox(playerid, achievementsbutton[playerid], 0);
PlayerTextDrawSetProportional(playerid, achievementsbutton[playerid], 1);
PlayerTextDrawSetSelectable(playerid, achievementsbutton[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, achievementsbutton[playerid], 19941);
PlayerTextDrawSetPreviewRot(playerid, achievementsbutton[playerid], -81.000000, 0.000000, -179.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, achievementsbutton[playerid], 1, 1);
**/
            PlayerTextDraw achievementsButton = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(447.0f, 186.0f), "Preview_Model");
            achievementsButton.Font = TextDrawFont.PreviewModel;
            achievementsButton.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            achievementsButton.Width = 17.0f;
            achievementsButton.Height = 17.5f;
            achievementsButton.Outline = 0;
            achievementsButton.Shadow = 0;
            achievementsButton.Alignment = TextDrawAlignment.Left;
            achievementsButton.ForeColor = -1;
            achievementsButton.BackColor = 125;
            achievementsButton.BoxColor = -16777103;
            achievementsButton.UseBox = false;
            achievementsButton.Proportional = true;
            achievementsButton.Selectable = true;
            achievementsButton.PreviewModel = 19941;
            achievementsButton.PreviewRotation = new SampSharp.GameMode.Vector3(-81.0, 0.0, -179.0);
            achievementsButton.PreviewZoom = 1;

            /**
WoodInvTXD[playerid] = CreatePlayerTextDraw(playerid, 476.000000, 111.000000, "Preview_Model");
PlayerTextDrawFont(playerid, WoodInvTXD[playerid], 5);
PlayerTextDrawLetterSize(playerid, WoodInvTXD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, WoodInvTXD[playerid], 30.000000, 35.000000);
PlayerTextDrawSetOutline(playerid, WoodInvTXD[playerid], 0);
PlayerTextDrawSetShadow(playerid, WoodInvTXD[playerid], 0);
PlayerTextDrawAlignment(playerid, WoodInvTXD[playerid], 1);
PlayerTextDrawColor(playerid, WoodInvTXD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, WoodInvTXD[playerid], 0);
PlayerTextDrawBoxColor(playerid, WoodInvTXD[playerid], -16777103);
PlayerTextDrawUseBox(playerid, WoodInvTXD[playerid], 0);
PlayerTextDrawSetProportional(playerid, WoodInvTXD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, WoodInvTXD[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, WoodInvTXD[playerid], 1463);
PlayerTextDrawSetPreviewRot(playerid, WoodInvTXD[playerid], -12.000000, 2.000000, 44.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, WoodInvTXD[playerid], 1, 1);
**/
            PlayerTextDraw woodInvTxd = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(476.0f, 111.0f), "Preview_Model");
            woodInvTxd.Font = TextDrawFont.PreviewModel;
            woodInvTxd.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            woodInvTxd.Width = 30.0f;
            woodInvTxd.Height = 35.0f;
            woodInvTxd.Outline = 0;
            woodInvTxd.Shadow = 0;
            woodInvTxd.Alignment = TextDrawAlignment.Left;
            woodInvTxd.ForeColor = -1;
            woodInvTxd.BackColor = 0;
            woodInvTxd.BoxColor = -16777103;
            woodInvTxd.UseBox = false;
            woodInvTxd.Proportional = true;
            woodInvTxd.Selectable = false;
            woodInvTxd.PreviewModel = 1463;
            woodInvTxd.PreviewRotation = new SampSharp.GameMode.Vector3(-12.0, 2.0, 44.0);
            woodInvTxd.PreviewZoom = 1;

            /**
RockInvTXD[playerid] = CreatePlayerTextDraw(playerid, 478.000000, 139.000000, "Preview_Model");
PlayerTextDrawFont(playerid, RockInvTXD[playerid], 5);
PlayerTextDrawLetterSize(playerid, RockInvTXD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, RockInvTXD[playerid], 23.500000, 21.500000);
PlayerTextDrawSetOutline(playerid, RockInvTXD[playerid], 0);
PlayerTextDrawSetShadow(playerid, RockInvTXD[playerid], 0);
PlayerTextDrawAlignment(playerid, RockInvTXD[playerid], 1);
PlayerTextDrawColor(playerid, RockInvTXD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, RockInvTXD[playerid], 0);
PlayerTextDrawBoxColor(playerid, RockInvTXD[playerid], -16777103);
PlayerTextDrawUseBox(playerid, RockInvTXD[playerid], 0);
PlayerTextDrawSetProportional(playerid, RockInvTXD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, RockInvTXD[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, RockInvTXD[playerid], 3929);
PlayerTextDrawSetPreviewRot(playerid, RockInvTXD[playerid], -12.000000, 2.000000, 44.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, RockInvTXD[playerid], 1, 1);
**/
            PlayerTextDraw rockInvTxd = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(478.0f, 139.0f), "Preview_Model");
            rockInvTxd.Font = TextDrawFont.PreviewModel;
            rockInvTxd.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            rockInvTxd.Width = 23.5f;
            rockInvTxd.Height = 21.5f;
            rockInvTxd.Outline = 0;
            rockInvTxd.Shadow = 0;
            rockInvTxd.Alignment = TextDrawAlignment.Left;
            rockInvTxd.ForeColor = -1;
            rockInvTxd.BackColor = 0;
            rockInvTxd.BoxColor = -16777103;
            rockInvTxd.UseBox = false;
            rockInvTxd.Proportional = true;
            rockInvTxd.Selectable = false;
            rockInvTxd.PreviewModel = 3929;
            rockInvTxd.PreviewRotation = new SampSharp.GameMode.Vector3(-12.0, 2.0, 44.0);
            rockInvTxd.PreviewZoom = 1;
            /**
IronInvTXD[playerid] = CreatePlayerTextDraw(playerid, 475.000000, 153.000000, "Preview_Model");
PlayerTextDrawFont(playerid, IronInvTXD[playerid], 5);
PlayerTextDrawLetterSize(playerid, IronInvTXD[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, IronInvTXD[playerid], 31.500000, 32.500000);
PlayerTextDrawSetOutline(playerid, IronInvTXD[playerid], 0);
PlayerTextDrawSetShadow(playerid, IronInvTXD[playerid], 0);
PlayerTextDrawAlignment(playerid, IronInvTXD[playerid], 1);
PlayerTextDrawColor(playerid, IronInvTXD[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, IronInvTXD[playerid], 0);
PlayerTextDrawBoxColor(playerid, IronInvTXD[playerid], -16777103);
PlayerTextDrawUseBox(playerid, IronInvTXD[playerid], 0);
PlayerTextDrawSetProportional(playerid, IronInvTXD[playerid], 1);
PlayerTextDrawSetSelectable(playerid, IronInvTXD[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, IronInvTXD[playerid], 2936);
PlayerTextDrawSetPreviewRot(playerid, IronInvTXD[playerid], -12.000000, 2.000000, 44.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, IronInvTXD[playerid], 1, 1);
**/
            PlayerTextDraw ironInvTxd = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(475.0f, 153.0f), "Preview_Model");
            ironInvTxd.Font = TextDrawFont.PreviewModel;
            ironInvTxd.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            ironInvTxd.Width = 31.5f;
            ironInvTxd.Height = 32.5f;
            ironInvTxd.Outline = 0;
            ironInvTxd.Shadow = 0;
            ironInvTxd.Alignment = TextDrawAlignment.Left;
            ironInvTxd.ForeColor = -1;
            ironInvTxd.BackColor = 0;
            ironInvTxd.BoxColor = -16777103;
            ironInvTxd.UseBox = false;
            ironInvTxd.Proportional = true;
            ironInvTxd.Selectable = false;
            ironInvTxd.PreviewModel = 2936;
            ironInvTxd.PreviewRotation = new SampSharp.GameMode.Vector3(-12.0, 2.0, 44.0);
            ironInvTxd.PreviewZoom = 1;
            /**
tkaninvtxd[playerid] = CreatePlayerTextDraw(playerid, 473.000000, 173.000000, "Preview_Model");
PlayerTextDrawFont(playerid, tkaninvtxd[playerid], 5);
PlayerTextDrawLetterSize(playerid, tkaninvtxd[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, tkaninvtxd[playerid], 36.500000, 31.500000);
PlayerTextDrawSetOutline(playerid, tkaninvtxd[playerid], 0);
PlayerTextDrawSetShadow(playerid, tkaninvtxd[playerid], 0);
PlayerTextDrawAlignment(playerid, tkaninvtxd[playerid], 1);
PlayerTextDrawColor(playerid, tkaninvtxd[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, tkaninvtxd[playerid], 0);
PlayerTextDrawBoxColor(playerid, tkaninvtxd[playerid], -16777103);
PlayerTextDrawUseBox(playerid, tkaninvtxd[playerid], 0);
PlayerTextDrawSetProportional(playerid, tkaninvtxd[playerid], 1);
PlayerTextDrawSetSelectable(playerid, tkaninvtxd[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, tkaninvtxd[playerid], 19518);
PlayerTextDrawSetPreviewRot(playerid, tkaninvtxd[playerid], 79.000000, 2.000000, 17.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, tkaninvtxd[playerid], 1, 1);
**/
            PlayerTextDraw tkanInvTxd = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(473.0f, 173.0f), "Preview_Model");
            tkanInvTxd.Font = TextDrawFont.PreviewModel;
            tkanInvTxd.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            tkanInvTxd.Width = 36.5f;
            tkanInvTxd.Height = 31.5f;
            tkanInvTxd.Outline = 0;
            tkanInvTxd.Shadow = 0;
            tkanInvTxd.Alignment = TextDrawAlignment.Left;
            tkanInvTxd.ForeColor = -1;
            tkanInvTxd.BackColor = 0;
            tkanInvTxd.BoxColor = -16777103;
            tkanInvTxd.UseBox = false;
            tkanInvTxd.Proportional = true;
            tkanInvTxd.Selectable = false;
            tkanInvTxd.PreviewModel = 19518;
            tkanInvTxd.PreviewRotation = new SampSharp.GameMode.Vector3(79.0, 2.0, 17.0);
            tkanInvTxd.PreviewZoom = 1;
            /**
weapon1[playerid] = CreatePlayerTextDraw(playerid, 375.000000, 210.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon1[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon1[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon1[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon1[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon1[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon1[playerid], 1);
PlayerTextDrawColor(playerid, weapon1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon1[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon1[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon1[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon1[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon1[playerid], 348);
PlayerTextDrawSetPreviewRot(playerid, weapon1[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon1[playerid], 1, 1);
**/
            PlayerTextDraw weaponslot1 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(375.0f, 210.0f), "Preview_Model");
            weaponslot1.Font = TextDrawFont.PreviewModel;
            weaponslot1.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot1.Width = 27.5f;
            weaponslot1.Height = 18.5f;
            weaponslot1.Outline = 0;
            weaponslot1.Shadow = 0;
            weaponslot1.Alignment = TextDrawAlignment.Left;
            weaponslot1.ForeColor = -1;
            weaponslot1.BackColor = -1094795651;
            weaponslot1.BoxColor = -16777103;
            weaponslot1.UseBox = false;
            weaponslot1.Proportional = true;
            weaponslot1.Selectable = true;
            weaponslot1.PreviewModel = 348;
            weaponslot1.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot1.PreviewZoom = 1;
            /**
weapon2[playerid] = CreatePlayerTextDraw(playerid, 407.000000, 210.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon2[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon2[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon2[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon2[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon2[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon2[playerid], 1);
PlayerTextDrawColor(playerid, weapon2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon2[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon2[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon2[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon2[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon2[playerid], 351);
PlayerTextDrawSetPreviewRot(playerid, weapon2[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon2[playerid], 1, 1);
**/
            PlayerTextDraw weaponslot2 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(407.0f, 210.0f), "Preview_Model");
            weaponslot2.Font = TextDrawFont.PreviewModel;
            weaponslot2.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot2.Width = 27.5f;
            weaponslot2.Height = 18.5f;
            weaponslot2.Outline = 0;
            weaponslot2.Shadow = 0;
            weaponslot2.Alignment = TextDrawAlignment.Left;
            weaponslot2.ForeColor = -1;
            weaponslot2.BackColor = -1094795651;
            weaponslot2.BoxColor = -16777103;
            weaponslot2.UseBox = false;
            weaponslot2.Proportional = true;
            weaponslot2.Selectable = true;
            weaponslot2.PreviewModel = 351;
            weaponslot2.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot2.PreviewZoom = 1;
            /**
weapon3[playerid] = CreatePlayerTextDraw(playerid, 439.000000, 210.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon3[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon3[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon3[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon3[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon3[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon3[playerid], 1);
PlayerTextDrawColor(playerid, weapon3[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon3[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon3[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon3[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon3[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon3[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon3[playerid], 353);
PlayerTextDrawSetPreviewRot(playerid, weapon3[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon3[playerid], 1, 1);

**/
            PlayerTextDraw weaponslot3 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(439.0f, 210.0f), "Preview_Model");
            weaponslot3.Font = TextDrawFont.PreviewModel;
            weaponslot3.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot3.Width = 27.5f;
            weaponslot3.Height = 18.5f;
            weaponslot3.Outline = 0;
            weaponslot3.Shadow = 0;
            weaponslot3.Alignment = TextDrawAlignment.Left;
            weaponslot3.ForeColor = -1;
            weaponslot3.BackColor = -1094795651;
            weaponslot3.BoxColor = -16777103;
            weaponslot3.UseBox = false;
            weaponslot3.Proportional = true;
            weaponslot3.Selectable = true;
            weaponslot3.PreviewModel = 353;
            weaponslot3.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot3.PreviewZoom = 1;
            /**
weapon4[playerid] = CreatePlayerTextDraw(playerid, 375.000000, 232.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon4[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon4[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon4[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon4[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon4[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon4[playerid], 1);
PlayerTextDrawColor(playerid, weapon4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon4[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon4[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon4[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon4[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon4[playerid], 366);
PlayerTextDrawSetPreviewRot(playerid, weapon4[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon4[playerid], 1, 1);
**/
            PlayerTextDraw weaponslot4 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(375.0f, 232.0f), "Preview_Model");
            weaponslot4.Font = TextDrawFont.PreviewModel;
            weaponslot4.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot4.Width = 27.5f;
            weaponslot4.Height = 18.5f;
            weaponslot4.Outline = 0;
            weaponslot4.Shadow = 0;
            weaponslot4.Alignment = TextDrawAlignment.Left;
            weaponslot4.ForeColor = -1;
            weaponslot4.BackColor = -1094795651;
            weaponslot4.BoxColor = -16777103;
            weaponslot4.UseBox = false;
            weaponslot4.Proportional = true;
            weaponslot4.Selectable = true;
            weaponslot4.PreviewModel = 366;
            weaponslot4.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot4.PreviewZoom = 1;
            /**
weapon5[playerid] = CreatePlayerTextDraw(playerid, 407.000000, 232.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon5[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon5[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon5[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon5[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon5[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon5[playerid], 1);
PlayerTextDrawColor(playerid, weapon5[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon5[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon5[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon5[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon5[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon5[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon5[playerid], 356);
PlayerTextDrawSetPreviewRot(playerid, weapon5[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon5[playerid], 1, 1);
**/
            PlayerTextDraw weaponslot5 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(407.0f, 232.0f), "Preview_Model");
            weaponslot5.Font = TextDrawFont.PreviewModel;
            weaponslot5.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot5.Width = 27.5f;
            weaponslot5.Height = 18.5f;
            weaponslot5.Outline = 0;
            weaponslot5.Shadow = 0;
            weaponslot5.Alignment = TextDrawAlignment.Left;
            weaponslot5.ForeColor = -1;
            weaponslot5.BackColor = -1094795651;
            weaponslot5.BoxColor = -16777103;
            weaponslot5.UseBox = false;
            weaponslot5.Proportional = true;
            weaponslot5.Selectable = true;
            weaponslot5.PreviewModel = 356;
            weaponslot5.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot5.PreviewZoom = 1;

            /**
weapon6[playerid] = CreatePlayerTextDraw(playerid, 439.000000, 232.000000, "Preview_Model");
PlayerTextDrawFont(playerid, weapon6[playerid], 5);
PlayerTextDrawLetterSize(playerid, weapon6[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, weapon6[playerid], 27.500000, 18.500000);
PlayerTextDrawSetOutline(playerid, weapon6[playerid], 0);
PlayerTextDrawSetShadow(playerid, weapon6[playerid], 0);
PlayerTextDrawAlignment(playerid, weapon6[playerid], 1);
PlayerTextDrawColor(playerid, weapon6[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, weapon6[playerid], -1094795651);
PlayerTextDrawBoxColor(playerid, weapon6[playerid], -16777103);
PlayerTextDrawUseBox(playerid, weapon6[playerid], 0);
PlayerTextDrawSetProportional(playerid, weapon6[playerid], 1);
PlayerTextDrawSetSelectable(playerid, weapon6[playerid], 1);
PlayerTextDrawSetPreviewModel(playerid, weapon6[playerid], 349);
PlayerTextDrawSetPreviewRot(playerid, weapon6[playerid], 3.000000, 0.000000, -131.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, weapon6[playerid], 1, 1);
**/
            PlayerTextDraw weaponslot6 = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(439.0f, 232.0f), "Preview_Model");
            weaponslot6.Font = TextDrawFont.PreviewModel;
            weaponslot6.LetterSize = new SampSharp.GameMode.Vector2(0.6f, 2.0f);
            weaponslot6.Width = 27.5f;
            weaponslot6.Height = 18.5f;
            weaponslot6.Outline = 0;
            weaponslot6.Shadow = 0;
            weaponslot6.Alignment = TextDrawAlignment.Left;
            weaponslot6.ForeColor = -1;
            weaponslot6.BackColor = -1094795651;
            weaponslot6.BoxColor = -16777103;
            weaponslot6.UseBox = false;
            weaponslot6.Proportional = true;
            weaponslot6.Selectable = true;
            weaponslot6.PreviewModel = 349;
            weaponslot6.PreviewRotation = new SampSharp.GameMode.Vector3(3.0, 0.0, -131.0);
            weaponslot6.PreviewZoom = 1;
            /**
infobackplate[playerid] = CreatePlayerTextDraw(playerid, 504.000000, 211.600006, "_");
PlayerTextDrawFont(playerid, infobackplate[playerid], 1);
PlayerTextDrawLetterSize(playerid, infobackplate[playerid], 0.004166, 1.700001);
PlayerTextDrawTextSize(playerid, infobackplate[playerid], 298.500000, 36.000000);
PlayerTextDrawSetOutline(playerid, infobackplate[playerid], 1);
PlayerTextDrawSetShadow(playerid, infobackplate[playerid], 0);
PlayerTextDrawAlignment(playerid, infobackplate[playerid], 2);
PlayerTextDrawColor(playerid, infobackplate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, infobackplate[playerid], 255);
PlayerTextDrawBoxColor(playerid, infobackplate[playerid], -759918674);
PlayerTextDrawUseBox(playerid, infobackplate[playerid], 1);
PlayerTextDrawSetProportional(playerid, infobackplate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, infobackplate[playerid], 0);
**/
            PlayerTextDraw infobackplate = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(504.0f, 211.600006f), "_");
            infobackplate.Font = TextDrawFont.Normal;
            infobackplate.LetterSize = new SampSharp.GameMode.Vector2(0.004166, 1.700001);
            infobackplate.Width = 298.5f;
            infobackplate.Height = 36.0f;
            infobackplate.Outline = 1;
            infobackplate.Shadow = 0;
            infobackplate.Alignment = TextDrawAlignment.Center;
            infobackplate.ForeColor = -1;
            infobackplate.BackColor = 255;
            infobackplate.BoxColor = -759918674;
            infobackplate.UseBox = true;
            infobackplate.Proportional = true;
            infobackplate.Selectable = false;
            /**
sellbackplate[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 211.600006, "_");
PlayerTextDrawFont(playerid, sellbackplate[playerid], 1);
PlayerTextDrawLetterSize(playerid, sellbackplate[playerid], 0.004166, 1.700001);
PlayerTextDrawTextSize(playerid, sellbackplate[playerid], 298.500000, 36.000000);
PlayerTextDrawSetOutline(playerid, sellbackplate[playerid], 1);
PlayerTextDrawSetShadow(playerid, sellbackplate[playerid], 0);
PlayerTextDrawAlignment(playerid, sellbackplate[playerid], 2);
PlayerTextDrawColor(playerid, sellbackplate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, sellbackplate[playerid], 255);
PlayerTextDrawBoxColor(playerid, sellbackplate[playerid], -759918674);
PlayerTextDrawUseBox(playerid, sellbackplate[playerid], 1);
PlayerTextDrawSetProportional(playerid, sellbackplate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, sellbackplate[playerid], 0);
**/
            PlayerTextDraw sellbackplate = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(553.0f, 211.600006f), "_");
            sellbackplate.Font = TextDrawFont.Normal;
            sellbackplate.LetterSize = new SampSharp.GameMode.Vector2(0.004166, 1.700001);
            sellbackplate.Width = 298.5f;
            sellbackplate.Height = 36.0f;
            sellbackplate.Outline = 1;
            sellbackplate.Shadow = 0;
            sellbackplate.Alignment = TextDrawAlignment.Center;
            sellbackplate.ForeColor = -1;
            sellbackplate.BackColor = 255;
            sellbackplate.BoxColor = -759918674;
            sellbackplate.UseBox = true;
            sellbackplate.Proportional = true;
            sellbackplate.Selectable = false;
            /**
usebackplate[playerid] = CreatePlayerTextDraw(playerid, 504.000000, 233.500000, "_");
PlayerTextDrawFont(playerid, usebackplate[playerid], 1);
PlayerTextDrawLetterSize(playerid, usebackplate[playerid], 0.004166, 1.700001);
PlayerTextDrawTextSize(playerid, usebackplate[playerid], 298.500000, 36.000000);
PlayerTextDrawSetOutline(playerid, usebackplate[playerid], 1);
PlayerTextDrawSetShadow(playerid, usebackplate[playerid], 0);
PlayerTextDrawAlignment(playerid, usebackplate[playerid], 2);
PlayerTextDrawColor(playerid, usebackplate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, usebackplate[playerid], 255);
PlayerTextDrawBoxColor(playerid, usebackplate[playerid], -759918674);
PlayerTextDrawUseBox(playerid, usebackplate[playerid], 1);
PlayerTextDrawSetProportional(playerid, usebackplate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, usebackplate[playerid], 0);
**/
            PlayerTextDraw usebackplate = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(504.0f, 233.5f), "_");
            usebackplate.Font = TextDrawFont.Normal;
            usebackplate.LetterSize = new SampSharp.GameMode.Vector2(0.004166, 1.700001);
            usebackplate.Width = 298.5f;
            usebackplate.Height = 36.0f;
            usebackplate.Outline = 1;
            usebackplate.Shadow = 0;
            usebackplate.Alignment = TextDrawAlignment.Center;
            usebackplate.ForeColor = -1;
            usebackplate.BackColor = 255;
            usebackplate.BoxColor = -759918674;
            usebackplate.UseBox = true;
            usebackplate.Proportional = true;
            usebackplate.Selectable = false;
            /**
dropbackplate[playerid] = CreatePlayerTextDraw(playerid, 553.000000, 233.500000, "_");
PlayerTextDrawFont(playerid, dropbackplate[playerid], 1);
PlayerTextDrawLetterSize(playerid, dropbackplate[playerid], 0.004166, 1.700001);
PlayerTextDrawTextSize(playerid, dropbackplate[playerid], 298.500000, 36.000000);
PlayerTextDrawSetOutline(playerid, dropbackplate[playerid], 1);
PlayerTextDrawSetShadow(playerid, dropbackplate[playerid], 0);
PlayerTextDrawAlignment(playerid, dropbackplate[playerid], 2);
PlayerTextDrawColor(playerid, dropbackplate[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, dropbackplate[playerid], 255);
PlayerTextDrawBoxColor(playerid, dropbackplate[playerid], -759918674);
PlayerTextDrawUseBox(playerid, dropbackplate[playerid], 1);
PlayerTextDrawSetProportional(playerid, dropbackplate[playerid], 1);
PlayerTextDrawSetSelectable(playerid, dropbackplate[playerid], 0);
**/
            PlayerTextDraw dropbackplate = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(553.0f, 233.5f), "_");
            dropbackplate.Font = TextDrawFont.Normal;
            dropbackplate.LetterSize = new SampSharp.GameMode.Vector2(0.004166, 1.700001);
            dropbackplate.Width = 298.5f;
            dropbackplate.Height = 36.0f;
            dropbackplate.Outline = 1;
            dropbackplate.Shadow = 0;
            dropbackplate.Alignment = TextDrawAlignment.Center;
            dropbackplate.ForeColor = -1;
            dropbackplate.BackColor = 255;
            dropbackplate.BoxColor = -759918674;
            dropbackplate.UseBox = true;
            dropbackplate.Proportional = true;
            dropbackplate.Selectable = false;
            /**
useText[playerid] = CreatePlayerTextDraw(playerid, 493.000000, 235.000000, "use");
PlayerTextDrawFont(playerid, useText[playerid], 2);
PlayerTextDrawLetterSize(playerid, useText[playerid], 0.287499, 1.149999);
PlayerTextDrawTextSize(playerid, useText[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, useText[playerid], 1);
PlayerTextDrawSetShadow(playerid, useText[playerid], 0);
PlayerTextDrawAlignment(playerid, useText[playerid], 1);
PlayerTextDrawColor(playerid, useText[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, useText[playerid], 255);
PlayerTextDrawBoxColor(playerid, useText[playerid], 50);
PlayerTextDrawUseBox(playerid, useText[playerid], 0);
PlayerTextDrawSetProportional(playerid, useText[playerid], 1);
PlayerTextDrawSetSelectable(playerid, useText[playerid], 1);
**/
            PlayerTextDraw usetext = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(493.0f, 235.0f), "use");
            usetext.Font = TextDrawFont.Slim;
            usetext.LetterSize = new SampSharp.GameMode.Vector2(0.287499, 1.149999);
            usetext.Width = 400.0f;
            usetext.Height = 17.0f;
            usetext.Outline = 1;
            usetext.Shadow = 0;
            usetext.Alignment = TextDrawAlignment.Left;
            usetext.ForeColor = -1;
            usetext.BackColor = 255;
            usetext.BoxColor = 50;
            usetext.UseBox = false;
            usetext.Proportional = true;
            usetext.Selectable = true;
            /**
selltext[playerid] = CreatePlayerTextDraw(playerid, 539.000000, 214.000000, "sell");
PlayerTextDrawFont(playerid, selltext[playerid], 2);
PlayerTextDrawLetterSize(playerid, selltext[playerid], 0.287499, 1.149999);
PlayerTextDrawTextSize(playerid, selltext[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, selltext[playerid], 1);
PlayerTextDrawSetShadow(playerid, selltext[playerid], 0);
PlayerTextDrawAlignment(playerid, selltext[playerid], 1);
PlayerTextDrawColor(playerid, selltext[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, selltext[playerid], 255);
PlayerTextDrawBoxColor(playerid, selltext[playerid], 50);
PlayerTextDrawUseBox(playerid, selltext[playerid], 0);
PlayerTextDrawSetProportional(playerid, selltext[playerid], 1);
PlayerTextDrawSetSelectable(playerid, selltext[playerid], 1);
**/
            PlayerTextDraw selltext = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(539.0f, 214.0f), "sell");
            selltext.Font = TextDrawFont.Slim;
            selltext.LetterSize = new SampSharp.GameMode.Vector2(0.287499, 1.149999);
            selltext.Width = 400.0f;
            selltext.Height = 17.0f;
            selltext.Outline = 1;
            selltext.Shadow = 0;
            selltext.Alignment = TextDrawAlignment.Left;
            selltext.ForeColor = -1;
            selltext.BackColor = 255;
            selltext.BoxColor = 50;
            selltext.UseBox = false;
            selltext.Proportional = true;
            selltext.Selectable = true;
            /**
droptext[playerid] = CreatePlayerTextDraw(playerid, 538.000000, 235.000000, "drop");
PlayerTextDrawFont(playerid, droptext[playerid], 2);
PlayerTextDrawLetterSize(playerid, droptext[playerid], 0.287499, 1.149999);
PlayerTextDrawTextSize(playerid, droptext[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, droptext[playerid], 1);
PlayerTextDrawSetShadow(playerid, droptext[playerid], 0);
PlayerTextDrawAlignment(playerid, droptext[playerid], 1);
PlayerTextDrawColor(playerid, droptext[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, droptext[playerid], 255);
PlayerTextDrawBoxColor(playerid, droptext[playerid], 50);
PlayerTextDrawUseBox(playerid, droptext[playerid], 0);
PlayerTextDrawSetProportional(playerid, droptext[playerid], 1);
PlayerTextDrawSetSelectable(playerid, droptext[playerid], 1);
**/
            PlayerTextDraw droptext = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(538.0f, 235.0f), "drop");
            droptext.Font = TextDrawFont.Slim;
            droptext.LetterSize = new SampSharp.GameMode.Vector2(0.287499, 1.149999);
            droptext.Width = 400.0f;
            droptext.Height = 17.0f;
            droptext.Outline = 1;
            droptext.Shadow = 0;
            droptext.Alignment = TextDrawAlignment.Left;
            droptext.ForeColor = -1;
            droptext.BackColor = 255;
            droptext.BoxColor = 50;
            droptext.UseBox = false;
            droptext.Proportional = true;
            droptext.Selectable = true;
            /**
infotext[playerid] = CreatePlayerTextDraw(playerid, 491.000000, 214.000000, "INFO");
PlayerTextDrawFont(playerid, infotext[playerid], 2);
PlayerTextDrawLetterSize(playerid, infotext[playerid], 0.287499, 1.149999);
PlayerTextDrawTextSize(playerid, infotext[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, infotext[playerid], 1);
PlayerTextDrawSetShadow(playerid, infotext[playerid], 0);
PlayerTextDrawAlignment(playerid, infotext[playerid], 1);
PlayerTextDrawColor(playerid, infotext[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, infotext[playerid], 255);
PlayerTextDrawBoxColor(playerid, infotext[playerid], 50);
PlayerTextDrawUseBox(playerid, infotext[playerid], 0);
PlayerTextDrawSetProportional(playerid, infotext[playerid], 1);
PlayerTextDrawSetSelectable(playerid, infotext[playerid], 1);
**/
            PlayerTextDraw infotext = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(491.0f, 214.0f), "info");
            infotext.Font = TextDrawFont.Slim;
            infotext.LetterSize = new SampSharp.GameMode.Vector2(0.287499, 1.149999);
            infotext.Width = 400.0f;
            infotext.Height = 17.0f;
            infotext.Outline = 1;
            infotext.Shadow = 0;
            infotext.Alignment = TextDrawAlignment.Left;
            infotext.ForeColor = -1;
            infotext.BackColor = 255;
            infotext.BoxColor = 50;
            infotext.UseBox = false;
            infotext.Proportional = true;
            infotext.Selectable = true;
            /**
        exitbutton[playerid] = CreatePlayerTextDraw(playerid, 568.000000, 110.000000, "ld_beat:cross");
        PlayerTextDrawFont(playerid, exitbutton[playerid], 4);
        PlayerTextDrawLetterSize(playerid, exitbutton[playerid], 0.600000, 2.000000);
        PlayerTextDrawTextSize(playerid, exitbutton[playerid], 12.500000, 12.500000);
        PlayerTextDrawSetOutline(playerid, exitbutton[playerid], 1);
        PlayerTextDrawSetShadow(playerid, exitbutton[playerid], 0);
        PlayerTextDrawAlignment(playerid, exitbutton[playerid], 1);
        PlayerTextDrawColor(playerid, exitbutton[playerid], -1);
        PlayerTextDrawBackgroundColor(playerid, exitbutton[playerid], 255);
        PlayerTextDrawBoxColor(playerid, exitbutton[playerid], 50);
        PlayerTextDrawUseBox(playerid, exitbutton[playerid], 1);
        PlayerTextDrawSetProportional(playerid, exitbutton[playerid], 1);
        PlayerTextDrawSetSelectable(playerid, exitbutton[playerid], 1);
        **/
            PlayerTextDraw closeinv = new PlayerTextDraw(p, new SampSharp.GameMode.Vector2(568.0f, 110.0f), "ld_beat:cross");
            closeinv.Font = TextDrawFont.DrawSprite;
            closeinv.LetterSize = new SampSharp.GameMode.Vector2(0.6, 2.0);
            closeinv.Width = 12.5f;
            closeinv.Height = 12.5f;
            closeinv.Outline = 1;
            closeinv.Shadow = 0;
            closeinv.Alignment = TextDrawAlignment.Left;
            closeinv.ForeColor = -1;
            closeinv.BackColor = 255;
            closeinv.BoxColor = 50;
            closeinv.UseBox = true;
            closeinv.Proportional = true;
            closeinv.Selectable = true;


            //INVENTORY UP_________________________________________________________________________________________________

        }
        public static void ShowInventory(Player p)
        {
            for(int i = 0; i < 25;  i++)
            {
                PlayerTextDraw.Find(p,i).Show();
            }
        }
        
    }
   
}
